### ISSUE TITLE
unibeautify beautifies only in root director

### ISSUE THREAD

**Issue by aaronspring** [Unibeautify/unibeautify#220]
**Describe the bug**
unibeautify beautifies only in root director

**To Reproduce**

my .unibeautifyrc.yml
```yaml
Markdown:
  beautifiers:
    - Prettier
  indent_size: 4
  indent_char: " "
  wrap_line_length: 80

Python:
  beautifiers:
    - Black
  indent_size: 4
  indent_char: " "
  wrap_line_length: 80
  wrap_prose: always
```

**Expected behavior**
beautify all files in package

**Error/Stack Traces**
it only beautifies the files in the root directory and not recursive in the folders

**System (please complete the following information):**
 - OS:
 - Version:
https://github.com/aaronspring/pymistral/pull/13

**Additional context**
I tried to google this and see in the documentation. Didnt find anything. Probably not a bug but rather my shortcoming of configuration.
