### ISSUE TITLE
CodeClimate configuration and rules

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/unibeautify#38]
Our current CodeClimate configuration consists of the below.  We should decide how best to have it configured for all of the repos (stuff like number of lines a file, number of lines in a method/function, etc).  Specifics can be found here:  https://docs.codeclimate.com/docs/maintainability

```yaml
version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
exclude_patterns:
- "dist/"
- "**/node_modules/"
- "/test/"
- "**/*.d.ts"
```
